# nginx proxy address - http://172.17.0.1:61007

name: letterspace
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: ghcr.io/dcodesdev/letterspace:latest
    container_name: letterspace-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: letterspace-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      DATABASE_URL: postgresql://${DB_USER_NAME:-letterspaceuser}:${DB_USER_PASS:-changeme_db_password}@letterspace-db:5432/${DB_CREATE_DATABASE_NAME:-letterspace}?schema=public
      JWT_SECRET: ${APP_SECRET_KEY:-changeme_secret_key_min_32_chars}
    ports:
      - '172.17.0.1:61007:5000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - letterspace
      - proxy
      - cloudflare
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/5000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://letterspace-app:5000'
      - 'cloudflare.hostname=letterspace.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.letterspace-app.entrypoints=http'
      - 'traefik.http.routers.letterspace-app-secure.tls=true'
      - 'traefik.http.routers.letterspace-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.letterspace-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.letterspace-app.middlewares=letterspace-app-https-redirect'
      - 'traefik.http.routers.letterspace-app-secure.entrypoints=https'
      - 'traefik.http.routers.letterspace-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.letterspace-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.letterspace-app-secure.service=letterspace-app'
      - 'traefik.http.services.letterspace-app.loadbalancer.server.port=5000'

  db:
    image: postgres:latest
    container_name: letterspace-db
    hostname: letterspace-db
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: letterspace-db
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-letterspace}
      POSTGRES_USER: ${DB_USER_NAME:-letterspaceuser}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
    volumes:
      - './volumes/data/db/postgres/letterspace:/var/lib/postgresql/data:rw'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - letterspace

networks:
  letterspace:
    name: letterspace
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
